unit TestStep;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, StepIntf, ValidationRuleIntf, Step, TestBaseClasses;

type
  // Test methods for class TStep

  TestTStep = class(TParseContext)
  strict private
    FStep: IStep;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure DeveriaRetornarONomeDoMetodoCorrespondente;
  end;

implementation

procedure TestTStep.DeveriaRetornarONomeDoMetodoCorrespondente;
begin
  FStep.Descricao := 'Dado que meu step é válido.';
  Specify.That(FStep.MetodoDeTeste).Should.Equal('DadoQueMeuStepEValido');
end;

procedure TestTStep.SetUp;
begin
  FStep := TStep.Create;
end;

procedure TestTStep.TearDown;
begin
  FStep := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTStep.Suite);
end.

