unit TestdCucuberList;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Classes, dCucuberListIntf, dCucuberList, dSpec, TestBaseClasses;

type
  // Test methods for class TDcucumberList

  TestTDcucumberList = class(TParseContext)
  strict private
    FCucumberList: ICucumberList;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure DeveriaSerValidoSeFuncaoDeValidacaoEh;
    procedure DeveriaSerValidaSeNaoInformeiNenhumaFuncaoDeValidacao;
    procedure DeveriaSerValidaSeTemAoMenosUmItemNaLista;
  end;

implementation

procedure TestTDcucumberList.SetUp;
begin
  FCucumberList := TCucumberList.Create;
end;

procedure TestTDcucumberList.TearDown;
begin
  FCucumberList := nil;
end;

procedure TestTDcucumberList.DeveriaSerValidaSeNaoInformeiNenhumaFuncaoDeValidacao;
begin
  Specify.That(FCucumberList.Valid).Should.Be.True;
end;

procedure TestTDcucumberList.DeveriaSerValidaSeTemAoMenosUmItemNaLista;
begin
  FCucumberList.Add(TCucumberList.Create);
  FCucumberList.ValidateFunction := function: Boolean
  begin
    Result := FCucumberList.Count > 0;
  end;
  Specify.That(FCucumberList.Valid).Should.Be.True;
end;

procedure TestTDcucumberList.DeveriaSerValidoSeFuncaoDeValidacaoEh;
begin
  FCucumberList.ValidateFunction := function: Boolean
  begin
    Result := True;
  end;
  Specify.That(FCucumberList.Valid).Should.Be.True;
end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTDcucumberList.Suite);

end.
